# Generated by Django 3.0.7 on 2020-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classes_semester_semesterresult_userinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='registration',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
