# Generated by Django 3.0.7 on 2020-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200714_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='birth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='citizenship',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='father_firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='mother_firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
