# Generated by Django 3.0.7 on 2020-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200714_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='birth',
            field=models.DateTimeField(),
        ),
    ]
